FROM ubuntu:18.04

MAINTAINER Yanick Egli-Rohr

RUN apt-get update && apt-get install -y apache2 && groupadd -r user_grp && useradd -r -g user_grp user
USER user

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_RUN_DIR /var/www/html

EXPOSE 80

CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]