# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

    # Provider Settings
	  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    end

  # Network Settings
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"
  
   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get -y install debconf-utils apache2 nmap
     sudo a2enmod ldap
     sudo mkdir -p  /var/www/html/data && sudo chown www-data:www-data /var/www/html/data 

   SHELL
end
