Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "mailserver"
  config.vm.network "private_network", ip: "192.168.10.150/24", virtualbox__intnet: "LAN"
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true  
  config.vm.provider "virtualbox" do |vb|
vb.memory = "512"  
end
config.vm.provision "shell", inline: <<-SHELL
sudo apt-get update

sudo apt-get install exim4 -y
sudo sed -i "s/dc_eximconfig_configtype='local'/dc_eximconfig_configtype='internet'/g" /etc/exim4/update-exim4.conf.conf
sudo sed -i "s/dc_other_hostnames='mailserver'/dc_other_hostnames='m300domain.com'/g" /etc/exim4/update-exim4.conf.conf
sudo sed -i "s/dc_local_interfaces='127.0.0.1 ; ::1'/dc_local_interfaces=''/g" /etc/exim4/update-exim4.conf.conf

bash /usr/share/doc/exim4-base/examples/exim-gencert

echo "MAIN_TLS_ENABLE=yes" >>  /etc/exim4/exim4.conf.template

# After every Config Service needs to be restarted
update-exim4.conf
service exim4 restart

sudo adduser yanickegli
sudo usermod -aG sudo yanickegli

SHELL
end