Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "firewall"
  config.vm.network "private_network", ip:"192.168.10.1/24", virtualbox__intnet: "LAN"  
  config.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"  
config.vm.provider "virtualbox" do |vb|
  vb.memory = "512"  
end
config.vm.provision "shell", inline: <<-SHELL

  #sudo apt-get install ufw
   sudo apt-get update
   sudo apt-get install ufw -y

  #Rules erstellen
   sudo ufw allow 80/tcp
   sudo ufw allow from any to any port 22

  #fire aktivieren
   sudo ufw enable

   sudo adduser yanickegli
   sudo usermod -aG sudo yanickegli
     
  SHELL
end
