# Wordpress Umgebung

version: '3'
services:
    httpd:
        image: httpd
        container_name: apache2_prod
        volumes: 
            - ./apacheconf:/etc/apache2/
        ports: 
            - 8080:80           
        restart: always   
        networks: 
            LAN:
                ipv4_address: 192.168.10.10

    wordpress:
        image: wordpress:latest
        container_name: wordpress_prod
        environment: 
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes: 
            - ./wordpressconf:/var/www/html
        ports: 
            - 4040:80
        restart: always
        depends_on:
            - mysql
        networks:
            LAN:
                ipv4_address: 192.168.10.20

    mysql:
        image: mysql:5.7
        container_name: mysql_prod
        environment: 
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        # volumes: 
        #    - ./mysqlconf:/etc/
        expose: 
            - "80"
        restart: always
        depends_on:
            - httpd
        networks:
            LAN:
                ipv4_address: 192.168.10.30

networks: 
    LAN:
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/24
